import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {api} from '../worker/api.js';
function fixture(){
 const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_steady_mentor.sql',import.meta.url),'utf8'));
 function prepare(sql){let args=[];return {bind(...a){args=a;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:db.prepare(sql).run(...args)};}};}
 const env={DB:{prepare,async batch(items){const out=[];for(const item of items)out.push(await item.run());return out;}},WALL_HASH_SECRET:'test-secret-only'};
 async function call(method='GET',path='/api/notes',data,ip='192.0.2.1',origin='https://wall.test'){const r=await api(new Request('https://wall.test'+path,{method,headers:{origin,'content-type':'application/json','cf-connecting-ip':ip},body:data===undefined?undefined:JSON.stringify(data)}),env,{waitUntil(p){p.catch(()=>{});}});return {status:r.status,data:await r.json()};}
 const note=()=>({id:randomUUID(),body:'Take one small step toward what matters.',direction:'Purpose',deleteToken:'a'.repeat(64),publishConsent:true});return {call,note,db,env};
}
test('shared notes persist, expose no removal keys, and require the correct key to delete',async()=>{const f=fixture(),n=f.note();assert.deepEqual((await f.call()).data.notes,[]);assert.equal((await f.call('POST','/api/notes',n)).status,201);assert.equal((await f.call('POST','/api/notes',n)).data.replayed,true);const list=(await f.call()).data.notes;assert.equal(list.length,1);assert.deepEqual(Object.keys(list[0]).sort(),['body','created_at','direction','id']);assert.equal((await f.call('DELETE','/api/notes/'+n.id,{deleteToken:'b'.repeat(64)})).status,404);assert.equal((await f.call('DELETE','/api/notes/'+n.id,{deleteToken:n.deleteToken})).status,200);assert.equal((await f.call()).data.notes.length,0);f.db.close();});
test('publishing requires explicit consent, same origin, safe plain text and rate limits',async()=>{const f=fixture();assert.equal((await f.call('POST','/api/notes',{...f.note(),publishConsent:false})).status,400);assert.equal((await f.call('POST','/api/notes',f.note(),'192.0.2.1','https://other.test')).status,403);for(const body of ['<script>alert(1)</script>','Contact a@b.com','https://spam.example','x'.repeat(241)])assert.equal((await f.call('POST','/api/notes',{...f.note(),body})).status,400);let r;for(let i=0;i<13;i++)r=await f.call('POST','/api/notes',f.note(),'192.0.2.2');assert.equal(r.status,429);f.db.close();});
test('repeated reports from distinct sources hide the note globally',async()=>{const f=fixture(),n=f.note();await f.call('POST','/api/notes',n);for(const ip of ['192.0.2.2','192.0.2.2'])await f.call('POST','/api/notes/'+n.id+'/report',{},ip);assert.equal((await f.call()).data.notes.length,1);for(const ip of ['192.0.2.3','192.0.2.4'])await f.call('POST','/api/notes/'+n.id+'/report',{},ip);assert.equal((await f.call()).data.notes.length,0);assert.equal((await f.call('DELETE','/api/notes/'+n.id,{deleteToken:n.deleteToken})).status,200);f.db.close();});
test('pagination has no duplicate notes and unavailable storage fails honestly',async()=>{const f=fixture();for(let i=0;i<10;i++)await f.call('POST','/api/notes',f.note());const first=(await f.call()).data;assert.equal(first.notes.length,8);const second=(await f.call('GET','/api/notes?before='+encodeURIComponent(first.next))).data;assert.equal(second.notes.length,2);assert.equal(new Set([...first.notes,...second.notes].map(n=>n.id)).size,10);assert.equal(second.next,null);assert.equal((await api(new Request('https://wall.test/api/notes'),{},{})).status,503);f.db.close();});
